# Generated by Django 3.2.14 on 2022-07-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20220714_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_link',
        ),
    ]
