# Generated by Django 4.0.5 on 2022-06-27 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idea.category')),
                ('ideas', models.ManyToManyField(blank=True, to='idea.idea')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_owner', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idea.subcategory')),
                ('users', models.ManyToManyField(blank=True, related_name='skill_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
