# Generated by Django 4.0.5 on 2022-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='skills',
            field=models.ManyToManyField(related_name='idea_skills', to='skill.skill'),
        ),
    ]
