# Generated by Django 4.0.5 on 2022-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_remove_idea_likes_idea_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='cat',
        ),
        migrations.AddField(
            model_name='idea',
            name='cat',
            field=models.ManyToManyField(to='idea.category'),
        ),
        migrations.RemoveField(
            model_name='idea',
            name='sub_cat',
        ),
        migrations.AddField(
            model_name='idea',
            name='sub_cat',
            field=models.ManyToManyField(to='idea.subcategory'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='cat',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ManyToManyField(to='idea.category'),
        ),
    ]
