# Generated by Django 4.0.5 on 2022-06-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('idea', '0003_remove_idea_cat_idea_cat_remove_idea_sub_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='skills',
            field=models.ManyToManyField(related_name='idea_skills', to='skill.skill'),
        ),
    ]
