# Generated by Django 3.2.14 on 2022-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='comment',
        ),
        migrations.AddField(
            model_name='idea',
            name='comment',
            field=models.ManyToManyField(related_name='idea_comments', to='idea.Comment'),
        ),
    ]
