# Generated by Django 3.2.14 on 2022-07-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20220714_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='comment',
            new_name='comments',
        ),
    ]
