# Generated by Django 3.2.14 on 2022-07-14 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0004_rename_comment_idea_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='users',
            field=models.ManyToManyField(related_name='idea_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='idea_comments', to='idea.Comment'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='idea_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
